### PR TITLE
auth-refactor

### PR DESCRIPTION
**Pull request by monsieur40a**
Refactored code to use a different auth workflow.  This auth workflow makes it so no browser window is needed to refresh tokens.

I also ran through the samples and changed the auth flow there too, same with testing.

The following samples I was unable to get to work fully:
use_watchlists.py - I have no watchlists created
use_user_info.py - issue with updating user preferences, needs to be looked at
use_saved_orders.py - I have no saved orders created

I also changed the logging a bit. There's now a logging file to get a logger from:  td/logging/create_logger.py

I put sample a sample config file in as well.

### CODE REVIEW

**Comment by monsieur40a** [comment]
logging has a concurrency error atm, need to fix still

**Comment by monsieur40a** [comment]
Updated logging to the module level (e.g. __name__) which should hopefully resolve concurrency issues for now. Eventually probably going to make it so you can have multiple client/session/credentials... need to figure how which would make sense still in terms of a trading bot framework.

**Comment by monsieur40a** [comment]
I just realized my version was built with config directly in td/, which is an issue for getting this via pip. I'll leave the refactoring to you/ someone else on that front. I've never made a pip package before and I'm not sure how to test that out fully.

**Comment by platypushunter** [comment]
@monsieur40a It would probably not be too difficult to change/add the functionality to make the config.ini a user defined location.

Some of the examples would need to be changed, and Honestly I think it would be a good starting point to kind of revamp the examples anyways. As is, they're a little out there and take some fiddling. I like the set up you have created here though. 

I will take a look at your repo and see what kind of changes i may be able to make

**Comment by platypushunter** [comment]
Taking a look at how you have it set up, it wouldn't be terribly complicated to get set up just a bit tedious.

My idea would be to create a class _config_ that when you call it you would pass it the directory/file for your config file. 

This _might_ be able to be added to another class, but I think it would be better to just add a new class.

**Comment by monsieur40a** [comment]
@platypushunter Were you able to get it to work at all? I have some random bug fixes in my branch too so it would be good to get it pulled in. Most are related to handling datetime though I believe.

**Comment by platypushunter** [comment]
@monsieur40a I was able to get it to work, sort of. I turned your system into class and added it to be more in line with the rest of the project, as far as conventions and documentation etc goes, but for some reason it gets to the point where it just opens a browser and then does nothing. I suspect its because the libraries you used aren't entirely compatible with windows (or so ive heard) and or im just doing something wrong.

I can add a pull request if you think youd be able to diagnose and fix the issue

**Pull request closed without merging**
